components:
  schemas: 
    Building:
      allOf: 
        - 
          $ref: "https://smart-data-models.github.io/dataModel.Building/Building/model.yaml#/Building"
      properties: 
        device:
          $ref: "https://github.com/brucelit/brucelit.github.io/blob/main/yaml/device.yaml"
        event: 
          description: "Upcoming or past event associated with this place, organization, or action."
          type: string
          x-ngsi: 
            model: "https://schema.org/Text"
            type: Relationship
            uri: "https://schema.org/event"
            uri-prefix: "https://schema.org/"
        person: 
          $ref: "https://github.com/brucelit/brucelit.github.io/blob/main/yaml/person.yaml"
info:
  description:  |
    Information on a given Building
  title: Building
  version: "1.0.0"
openapi: "3.0.0"
    
paths:
  /:
    get:
      responses:
        200:
          description: OK
