components:
  schemas: 
    DeviceModel: 
      $ref: "https://smart-data-models.github.io/dataModel.Device/DeviceModel/model.yaml#/DeviceModel"
info:
  description:  |
    This entity captures the static properties of a Device. 
  title: DeviceModel
  version: "1.0.0"
openapi: "3.0.0"
    
paths:
  /:
    get:
      responses:
        200:
          description: OK
