--- 
components: 
  schemas: 
    Questionnaire: 
      description: |
          #### This entity contains a description of a questionnaire. 
          ---
      properties: 
        acceptedAnswer: 
          description: "The answer(s) that has been accepted as best, typically on a Question/Answer site."
          type: string
          x-ngsi: 
            model: "https://schema.org/Text"
            type: Property
            uri: "https://schema.org/acceptedAnswer"
            uri-prefix: "https://schema.org/"
        citation: 
          description: "The citation or reference to another work."
          type: string
          x-ngsi: 
            model: "https://schema.org/Text"
            type: Property
            uri: "https://schema.org/citation"
            uri-prefix: "https://schema.org/"
        countryOfOrigin: 
          description: "The country of the production company or individual responsible for the questions."
          type: string
          x-ngsi: 
            model: "https://schema.org/Text"
            type: Property
            uri: "https://schema.org/countryOfOrigin"
            uri-prefix: "https://schema.org/"
        dateModified: 
          description: "The date on which the CreativeWork was most recently modified or when the item's entry was modified within a DataFeed."
          type: string
          x-ngsi: 
            model: "https://schema.org/Text"
            type: Property
            uri: "https://schema.org/dateModified"
            uri-prefix: "https://schema.org/"
        locationCreated: 
          description: "The country of the production company or individual responsible for the questions."
          type: string
          x-ngsi: 
            model: "https://schema.org/Text"
            type: Property
            uri: "https://schema.org/locationCreated"
            uri-prefix: "https://schema.org/"
        provider: 
          description: "The person or organization who produced the questionnaires."
          type: string
          x-ngsi: 
            model: "https://schema.org/Text"
            type: Property
            uri: "https://schema.org/provider"
            uri-prefix: "https://schema.org/"
        size:
          description: "The person or organization who produced the questionnaires."
          type: integer
          x-ngsi: 
            model: "https://schema.org/Text"
            type: Property
            uri: "https://schema.org/size"
            uri-prefix: "https://schema.org/"
        text:
          description: "The textual content of the question."
          type: integer
          x-ngsi: 
            model: "https://schema.org/Text"
            type: Property
            uri: "https://schema.org/text"
            uri-prefix: "https://schema.org/"
      required: 
        - address
        - category
      type: object
      
openapi: 3.0.0
info:
  version: 0.0.0
  title: Questionnaire
    
paths:
  /:
    get:
      responses:
        200:
          description: OK
